# Conda environment file for developers
name: skreport-dev
channels:
  - conda-forge
  - defaults
dependencies:
# Packages required for development
  - conda
  - mamba
  - boa
  - conda-build
  - conda-verify
  # testing
  - pytest
  - pylint
  - pre-commit=2.*
# Packages required by the user to run it
  - python=3.8
  - python-pptx=0.6.21
  - matplotlib=3.1.3
  - PyYAML=5.3.1
  - numpy=1.18.5
  - pandas=1.0.5
  - pyside2=5.13.2
  - openpyxl=3.0.9
  - rich=10.16.2
  - pydantic=1.9.0
  # docs
  - sphinx=4.3
  - pydata-sphinx-theme=0.7
  - sphinx-autobuild=0.7
  - sphinx-argparse=0.2.5
  - sphinx-panels=0.6
  - sphinx-copybutton=0.4
  - sphinx-gallery=0.10
  - python-dotenv=0.19
  - sphinx-github-changelog==1.2.0
  - pip=22.0.4

